apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-api-deployment
  namespace: crypto-project
  labels:
    app: crypto-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-api # Sagt dem Master-Server, dass Statefulset alle Pods mit diesem Namen verwaltet.
      # Das Label für die Pods wird im template.metadata.labels definiert und ist somit das gleiche, wie das Label, das der Service sucht, um die Anfragen weiterzuleiten.
  template:
    metadata:
      labels:
        app: crypto-api # Label des Pods, das vom Service gesucht wird. Zudem werden auch über kubectl get all -l app=rabbitmq Infos angezeigt.
    spec:
      containers:
      - name: api-service
        image: fgrothaus1/crypto-backend:3757b7f54e3848f7fb5b544b6dba9fbf8b897c30
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: api-port
        envFrom: # Anweisung, um die Variablen aus der ConfigMap/Secret in die Container-Umgebung zu laden.
        - configMapRef:
            name: backend-config
        resources:
          requests:
            memory: "64Mi"      # Mindestbedarf an RAM beim Start
            cpu: "100m"         # Mindestbedarf an CPU (0,1 Kern)
          limits:
            memory: "256Mi"     # Harte RAM-Grenze
            cpu: "500m"         # Maximale CPU-Leistung (0,5 Kerne)
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5  # 5s warten nach Containerstart, bevor geprüft wird
          periodSeconds: 10       # Alle 10s prüfen
        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20