apiVersion: v1
kind: Service
metadata:
  name: crypto-api-service
  namespace: crypto-project
spec:
  selector:
    app: crypto-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: api-port
  type: ClusterIP