apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: crypto-project
data:
  PYTHONUNBUFFERED: "1" # Um sich livelogs aus der Anwendung anzeigen zu lassen
  REDIS_URL: "redis://redis:6379"
  RABBITMQ_CONNECTION_STRING: "amqp://guest:guest@rabbitmq:5672/"