apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-consumer-deployment
  namespace: crypto-project
  labels:
    app: crypto-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-consumer
  template:
    metadata:
      labels:
        app: crypto-consumer
    spec:
      containers:
      - name: consumer-service
        image: fgrothaus1/crypto-backend:b50375b500b57454a83084e8948f57babcda7fa1
        imagePullPolicy: Always
        command: ["python", "consumer.py"]
        envFrom:
        - configMapRef:
            name: backend-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"