apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-frontend-deployment
  namespace: crypto-project
  labels:
    app: crypto-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-frontend
  template:
    metadata:
      labels:
        app: crypto-frontend
    spec:
      containers:
      - name: frontend-service
        image: fgrothaus1/crypto-frontend:3757b7f54e3848f7fb5b544b6dba9fbf8b897c30
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web-port
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"