apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crypto-pipeline-ingress
  namespace: default
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  # 1. Regel: Wenn du das Frontend aufrufst
  - host: crypto.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crypto-frontend-service
            port:
              number: 80
  # 2. Regel: Das, worauf dein Code brennt – die API inklusive WebSockets!
  - host: api.crypto.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crypto-api-service
            port:
              number: 8000