apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-ingestion-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-ingestion
  template:
    metadata:
      labels:
        app: crypto-ingestion
    spec:
      containers:
      - name: ingestion-service
        image: fgrothaus1/crypto-ingestion:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: ingestion-config
        - secretRef:
            name: ingestion-secret # untracked file. Wird lokal mit kubectl eingebunden